/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __SUSFS_LSM_HOOK_H
#define __SUSFS_LSM_HOOK_H

#include <linux/lsm_hooks.h>
#include <linux/stddef.h>
#include <linux/version.h>

#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
#define KSU_LSM_HOOK_HEADS_TYPE struct lsm_static_calls_table
#else
#define KSU_LSM_HOOK_HEADS_TYPE struct security_hook_heads
#endif

struct ksu_lsm_hook {
    const char *head_name;
    const char *target_name;
    size_t head_offset;
    size_t hook_offset;
    void *replacement;
    void *original;
    struct security_hook_list *entry;
    /* true = get in front of every registered LSM instead of overwriting the slot of an
     * entry resolved by symbol name (see lsm_hook.c).  WHAT that means depends on the
     * kernel:
     *
     *   < 6.12   our own struct security_hook_list is put at the HEAD of the hook's
     *            hlist.  It runs before every registered LSM (SELinux included), so it
     *            can only ADD a denial (-ENOENT) and can never suppress another LSM's
     *            decision - which is why its replacement must NOT call any original and
     *            must return 0 on the pass-through path.  target_name/original stay
     *            unused here.
     *   >= 6.12  there is no list to insert into (dispatch is a static call per hook and
     *            LSM slot), so SELinux's own slot is taken over instead and the function
     *            displaced from it IS called on the pass-through path (hook->original via
     *            SUS_LSM_PASS_ORIG()): a plain `return 0` there would not continue any
     *            chain, it would silently drop SELinux for that hook.  Same "can only add
     *            a denial" property - the denial comes from returning -ENOENT before the
     *            original is reached. */
    bool insert;
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
    struct lsm_static_call *scall;
#else
    struct security_hook_list list;
#endif
    /* the offset from target_name to the real hook target */
    int offset;
};

#define KSU_LSM_HOOK_INIT(member, target_symbol, replacement_fn, off)                                                  \
    {                                                                                                                  \
        .head_name = #member, .target_name = target_symbol, .head_offset = offsetof(KSU_LSM_HOOK_HEADS_TYPE, member),  \
        .hook_offset = offsetof(struct security_hook_list, hook.member), .replacement = (void *)(replacement_fn),      \
        .offset = off,                                                                                                 \
    }

/* Insert-shaped initialiser: no symbol is resolved by name (nothing to find), so there
 * is no target_name and `original` starts NULL.  On < 6.12 the list head is addressed
 * through head_offset on struct security_hook_heads and cross-checked against the
 * kernel's own registration before anything is patched (see ksu_lsm_hook_head_at() in
 * lsm_hook.c); `original` is filled from the slot the takeover displaces only on
 * >= 6.12, where head_offset is the offset of this hook's struct lsm_static_call ARRAY
 * inside struct lsm_static_calls_table (its members are generated by LSM_HOOK(), so
 * offsetof() resolves there exactly like it does for the hlist heads - the table is
 * __randomize_layout, and lsm_hook.c validates the offset against the live table before
 * writing anything). */
#define KSU_LSM_HOOK_INSERT(member, replacement_fn)                                          \
    {                                                                                        \
        .head_name = #member, .head_offset = offsetof(KSU_LSM_HOOK_HEADS_TYPE, member),       \
        .hook_offset = offsetof(struct security_hook_list, hook.member),                      \
        .replacement = (void *)(replacement_fn), .insert = true,                              \
    }

/* Runtime patching of existing LSM hook slots (workaround for out-of-tree
 * modules; the normal path is security_add_hooks()).  Coherent via
 * text patching + RCU synchronization. */

int ksu_lsm_hook(struct ksu_lsm_hook *hook);
void ksu_lsm_unhook(struct ksu_lsm_hook *hook);

int ksu_register_lsm_hook(struct ksu_lsm_hook *hook);
void ksu_unregister_lsm_hook(struct ksu_lsm_hook *hook);

void ksu_lsm_hook_init(void);
void ksu_lsm_hook_exit(void);

#endif
